---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific variables (Amazon Linux)
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Amazon'

- name: Prepare environment (Amazon Linux)
  ansible.builtin.include_tasks: "prepare-{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Amazon' and php_remove_al2_extras_packages

- name: "Setup - PHP {{ php_version }}"
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: "Install OCI8 - PHP {{ php_version }}"
  ansible.builtin.include_tasks: "oci8-{{ ansible_os_family }}.yml"
  when: php_install_oci8_extension

- name: "Install Xdebug - PHP {{ php_version }}"
  ansible.builtin.package:
    name: "{{ php_xdebug_package }}"
    state: present
  become: true
  when: php_install_xdebug
