---
- name: Import Yum GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  become: true
  loop: "{{ php_imported_gpg_keys }}"

- name: Enable Yum repositories
  ansible.builtin.yum:
    name: "{{ php_enabled_yum_repos }}"
    state: present
  register: result
  until: result is succeeded
  retries: 15
  delay: 20
  become: true

- name: Install Yum PHP packages
  ansible.builtin.yum:
    name: "{{ php_installed_packages + php_installed_packages_extra }}"
    state: present
  become: true
