---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Include OS-specific tests
      include_tasks: "verify-{{ ansible_os_family }}.yml"
      loop:
        - "7.4"
        - "8.0"
        - "8.1"
      loop_control:
        loop_var: version
