---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazonlinux2-${CI_JOB_ID:-0}
    image: code.europa.eu:4567/ecgalaxy/amazonlinux2-ansible:latest
    pre_build_image: true
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
