---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Include OS-specific tests
      include_tasks: "verify-Amazon.yml"
      loop:
        - "8.1"
        - "8.2"
        - "8.3"
      loop_control:
        loop_var: version
