---
- name: Converge
  hosts: all
  roles:
    - ecgalaxy.bootstrap
    - ecgalaxy.common_packages
    - ecgalaxy.oracle_instantclient
  tasks:
    - name: Include php role
      ansible.builtin.include_role:
        name: php
      vars:
        php_version: "{{ version }}"
      loop:
        - "8.1"
        - "8.2"
      loop_control:
        loop_var: version
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
