---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Include OS-specific tests
      include_tasks: "verify-{{ ansible_os_family }}.yml"
      loop:
        - "8.2"
        - "8.3"
        - "8.4"
        - "8.5"
      loop_control:
        loop_var: version
